### ISSUE TITLE
Alignment issues in project section

### ISSUE THREAD

**Issue by harshitgupta028** [harshitg123/portfolio#22]
In the project section, the buttons are not properly aligned with other project

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/7840ae0d-bf27-45a4-86f2-5537a0aa9dad">

**Comment by FullStackWebDeveloper-HARSH** [comment]
Proposed Design Options

**Option 1: Flexbox Layout**
**Description:** Use CSS Flexbox to align the project buttons consistently within each project container.
Implementation:
**Advantages:**
->Simple and straightforward to implement.
->Ensures consistent alignment across different screen sizes.
**Disadvantages:**
->Requires adjusting the width and margin values to ensure proper spacing.

**Option 2: CSS Grid Layout**
**Description:** Utilize CSS Grid to ensure that all elements within the project section are consistently aligned.
Implementation:
**Advantages:**
->More control over the layout, especially for complex designs.
->Automatically adjusts the number of columns based on screen size.
Disadvantages:
->Slightly more complex to implement compared to Flexbox.

**Time Estimate**
Analysis and Planning: 2 hours
Implementation:
Flexbox Layout: 4 hours
CSS Grid Layout: 6 hours
Testing and Adjustments: 3 hours

**Total Estimate:**
Flexbox Layout: 9 hours
CSS Grid Layout: 11 hours

**Comment by harshitgupta028** [comment]
Hi @FullStackWebDeveloper-HARSH, thanks for the Proposed Design Options.

current implementation of all the sections is with **CSS Grid Layout** you can see the portfolio here https://portfolio-4rsg.onrender.com/ in case you didn't see it.

Also, you can create a pull request if you have fixed the alignment I'll review it and merge it to the main branch.

Steps to raise a pull request.

1. Fork the repo.
2. Clone it on your local.
3. Create the new branch.
4. Fix the issue.
5. Push the changes to your forked repo.
6. Then raise a pull request to the original repo.

You can also follow this official guide to contribute https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

regards,
Harshit.

**Comment by FullStackWebDeveloper-HARSH** [comment]
**Subject: Pull Request Raised for Issue #22**

Hi Harshit,
I wanted to inform you that I have raised a Pull Request to address Issue #22 in your portfolio repository. The changes involve adjusting the position of the .project__buttons div to improve the layout. Below are the details of the PR:

**Pull Request:** https://github.com/harshitgupta028/portfolio/pull/25

**Description:**
->This PR addresses Issue #22 by adding a new CSS class .robotic-view to adjust the top property and move the .project__buttons div upwards.

**Changes:**
->Added a new CSS class .robotic-view to adjust the top property and move the .project__buttons div upwards.
->Updated the HTML to include the .robotic-view class for the relevant div.

**Testing:**
->Verified that the buttons are correctly aligned across different screen sizes.
->Ensured that the layout remains responsive and visually consistent.
->Please review the PR at your convenience and let me know if there are any further adjustments needed.

Thank you for considering my contribution.
Best regards,
Harsh.

**Comment by harshitgupta028** [comment]
Hi @FullStackWebDeveloper-HARSH,

I've reviewed your code change, I appreciate your solution but I've requested some changes in it you can check the PR comment, I've written the detailed comment/feedback.

You can submit the PR with that change, I will review and merge it.

regards,
Harshit.
